const collectionNameMapping = new Map([
  ["Aris_Collection", "Alice"],
  ["CH0058_Collection", "Hifumi_Swimsuit"],
  ["CH0060_Collection", "Tsurugi_Swimsuit"],
  ["CH0063_Collection", "Hina_Swimsuit"],
  ["CH0064_Collection", "Iori_Swimsuit"],
  ["CH0066_Collection", "Shun_Little_Girl"],
  ["CH0069_Collection", "Mika"],
  ["CH0086_Collection", "Kayoko_Newyear"],
  ["CH0087_Collection", "Haruka_Newyear"],
  ["CH0088_Collection", "Megu"],
  ["CH0092_Collection", "Nonomi_Swimsuit"],
  ["CH0095_Collection", "Noa"],
  ["CH0098_Collection", "Asuna_BunnyGirl"],
  ["CH0099_Collection", "Akane_BunnyGirl"],
  ["CH0100_Collection", "Karin_BunnyGirl"],
  ["CH0101_Collection", "Neru_BunnyGirl"],
  ["CH0107_Collection", "Kaho"],
  ["CH0113_Collection", "Michiru"],
  ["CH0114_Collection", "Tsukuyo"],
  ["CH0123_Collection", "Shigure_Hotspring"],
  ["CH0137_Collection", "Kokona"],
  ["CH0141_Collection", "Fubuki"],
  ["CH0144_Collection", "Saki"],
  ["CH0145_Collection", "Miyu"],
  ["CH0155_Collection", "Natsu"],
  ["CH0156_Collection", "Iroha"],
  ["CH0160_Collection", "Chihiro"],
  ["CH0163_Collection", "Chinatsu_Hotspring"],
  ["CH0164_Collection", "Cherino_Hotspring"],
  ["CH0165_Collection", "Nodoka_Hotspring"],
  ["CH0167_Collection", "Reisa"],
  ["CH0169_Collection", "Ui"],
  ["CH0170_Collection", "Kanna"],
  ["CH0175_Collection", "Wakamo_Swimsuit"],
  ["CH0176_Collection", "Ayane"],
  ["CH0178_Collection", "Chise_Swimsuit"],
  ["CH0179_Collection", "Izuna_Swimsuit"],
  ["CH0180_Collection", "Shizuko_Swimsuit"],
  ["CH0182_Collection", "Utaha_Cheer"],
  ["CH0183_Collection", "Mimori_Swimsuit"],
  ["CH0185_Collection", "Kotori_Cheer"],
  ["CH0188_Collection", "Shiroko_Swimsuit"],
  ["CH0190_Collection", "Hasumi"],
  ["Hihumi_Collection", "Hifumi"],
  ["NP0013_Collection", "Ayumu"],
  ["Zunko_Collection", "Junko"],
]);

export function convertBACollectionImage(img: string) {
  if (collectionNameMapping.has(img)) {
    return collectionNameMapping.get(img)!;
  }
  return img.substring(0, img.length - "_Collection".length);
}
